### ISSUE TITLE
Conda-forge package 

### ISSUE THREAD

**Issue by jan-janssen** [PhasesResearchLab/PyQAlloy#1]
Hi @amkrajewski 

I just noticed there is not a `conda-forge` package for `PyQAlloy`. So I created one: 
https://anaconda.org/conda-forge/pyqalloy

Do you want to join me in maintaining it? 

Best, 

Jan

**Comment by amkrajewski** [comment]
Hi @jan-janssen

Thank you for putting it on conda-forge!

Sure! How can I do that?

Adam

**Comment by jan-janssen** [comment]
I added you to the repository, you should have received a Github notification. Alternatively you can got to https://github.com/orgs/conda-forge/invitation to accept the invitation.

**Comment by amkrajewski** [comment]
Thanks for setting everything up! I will close the issue now, but please feel free to reach out if I can improve anything :)
